# Generated by Django 5.1.2 on 2024-11-26 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
