# Generated by Django 5.1.2 on 2024-11-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_post_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='wrap',
            name='top_genres',
        ),
        migrations.AddField(
            model_name='wrap',
            name='top_genres',
            field=models.ManyToManyField(to='accounts.genre'),
        ),
    ]
