# Generated by Django 5.1.2 on 2024-11-14 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wrap",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wraps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
