# Generated by Django 5.1.2 on 2024-11-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_genre_remove_wrap_top_genres_wrap_top_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
