# Generated by Django 5.1.2 on 2024-11-17 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_wrap_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
