# Generated by Django 5.1.2 on 2024-12-01 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_post_liked_by"),
        ("accounts", "0005_alter_post_liked_by"),
    ]

    operations = []
